const validationRules = {
    identifier1: {
        assetTypeId: 6,
        fieldId: 1,
        hasValue: true,
        id: 1,
        invalidChar: "Q,O,I",
        isLookupField: false,
        lookupTable: null,
        maxLength: 17,
        minLength: 7,
        regex: "/^[0-9A-HJ-NPR-Z]+$/i",
    },
    make: {
        assetTypeId: 6,
        fieldId: 6,
        hasValue: true,
        id: 2,
        invalidChar: null,
        isLookupField: true,
        lookupTable: "Make",
        maxLength: null,
        minLength: null,
        regex: null,
    },
    branchRef: {
        assetTypeId: 6,
        fieldId: 27,
        hasValue: true,
        id: 3,
        invalidChar: null,
        isLookupField: true,
        lookupTable: "Branch",
        maxLength: null,
        minLength: null,
        regex: null,
    },
    identifier2: {
        assetTypeId: 6,
        fieldId: 2,
        hasValue: true,
        id: 4,
        invalidChar: null,
        isLookupField: false,
        lookupTable: null,
        maxLength: null,
        minLength: null,
        regex: null,
    },
    locationRef: {
        assetTypeId: 6,
        fieldId: 33,
        hasValue: true,
        id: 8,
        invalidChar: null,
        isLookupField: true,
        lookupTable: "Location",
        maxLength: null,
        minLength: null,
        regex: null,
    },
};

export default validationRules;
