export default {
    byId: {
        59483: 0,
        59484: 1,
        59485: 2,
        59486: 3,
    },
    data: [
        {
            assetAttributes: [],
            assetCore: {
                id: 1,
                identifier1: "WBA36BG080N071525",
                identifier2: "01/N015240",
                identifier3: "",
                identifier4: "",
                make: 199,
                type: 6,
            },
            auditLocation: {
                audit: {
                    branch: {
                        id: 22,
                        name: "ABC Motors - Dublin",
                    },
                    endDate: "2022-03-31 09:21:01+00:00",
                    id: 664,
                    name: "ABC Motors - Dublin/10 Mar 2022 14:51",
                    organisation: {
                        id: 4,
                        name: "ABC Bank",
                    },
                    startDate: "2022-03-10 09:21:01.814000+00:00",
                },
                id: 699,
                location: {
                    id: 18,
                    name: "15 Main St, Blackrock, Co. Dublin, A94 T8P8",
                },
            },
            excludeFrom: "None",
            excludeUntil: "None",
            id: 59483,
            isApproved: null,
            isAssigned: false,
            isExpected: true,
            isMandatory: true,
            isRelated: true,
            reissuedStatus: null,
            deferredTimestamp: 0,
        },
        {
            assetAttributes: [],
            assetCore: {
                id: 2,
                identifier1: "WBA32BL060CG80970",
                identifier2: "01/N015318",
                identifier3: "",
                identifier4: "",
                make: 199,
                type: 6,
            },
            auditLocation: {
                audit: {
                    branch: {
                        id: 22,
                        name: "ABC Motors - Dublin",
                    },
                    endDate: "2022-03-31 09:21:01+00:00",
                    id: 664,
                    name: "ABC Motors - Dublin/10 Mar 2022 14:51",
                    organisation: {
                        id: 4,
                        name: "ABC Bank",
                    },
                    startDate: "2022-03-10 09:21:01.814000+00:00",
                },
                id: 699,
                location: {
                    id: 18,
                    name: "15 Main St, Blackrock, Co. Dublin, A94 T8P8",
                },
            },
            excludeFrom: "None",
            excludeUntil: "None",
            id: 59484,
            isApproved: null,
            isAssigned: false,
            isExpected: true,
            isMandatory: true,
            isRelated: true,
            reissuedStatus: null,
            deferredTimestamp: 0,
        },
        {
            assetAttributes: [],
            assetCore: {
                id: 1,
                identifier1: "WBA36BG080N071525",
                identifier2: "01/N015240",
                identifier3: "",
                identifier4: "",
                make: 199,
                type: 6,
            },
            auditLocation: {
                audit: {
                    branch: {
                        id: 22,
                        name: "ABC Motors - Dublin",
                    },
                    endDate: "2022-03-31 09:21:01+00:00",
                    id: 664,
                    name: "ABC Motors - Dublin/10 Mar 2022 14:51",
                    organisation: {
                        id: 4,
                        name: "ABC Bank",
                    },
                    startDate: "2022-03-10 09:21:01.814000+00:00",
                },
                id: 699,
                location: {
                    id: 18,
                    name: "15 Main St, Blackrock, Co. Dublin, A94 T8P8",
                },
            },
            excludeFrom: "None",
            excludeUntil: "None",
            id: 59485,
            isApproved: null,
            isAssigned: false,
            isExpected: true,
            isMandatory: true,
            isRelated: true,
            reissuedStatus: null,
            deferredTimestamp: 0,
        },
        {
            assetAttributes: [],
            assetCore: {
                id: 26532,
                identifier1: "ZFA22300005655675",
                identifier2: "76D1234",
                identifier3: null,
                identifier4: null,
                make: 1,
                type: 6,
            },
            auditLocation: {
                audit: {
                    branch: {
                        id: 22,
                        name: "ABC Motors - Dublin",
                    },
                    endDate: "2022-03-31 09:21:01+00:00",
                    id: 664,
                    name: "ABC Motors - Dublin/10 Mar 2022 14:51",
                    organisation: {
                        id: 4,
                        name: "ABC Bank",
                    },
                    startDate: "2022-03-10 09:21:01.814000+00:00",
                },
                id: 699,
                location: {
                    id: 18,
                    name: "15 Main St, Blackrock, Co. Dublin, A94 T8P8",
                },
            },
            excludeFrom: "None",
            excludeUntil: "None",
            id: 59486,
            isApproved: null,
            isAssigned: false,
            isExpected: true,
            isMandatory: true,
            isRelated: true,
            reissuedStatus: null,
            deferredTimestamp: 0,
        },
    ],
    item: null,
};
